name: Release
on:
  push:
    branches:
      - main  

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
          npm install semantic-release @semantic-release/git @semantic-release/github

      - name: Build with PyInstaller
        run: pyinstaller --onefile rename_images.py

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        if: ${{ env.NEW_RELEASE_PUBLISHED == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.NEW_RELEASE_UPLOAD_URL }}
          asset_path: ./dist/rename_images.exe
          asset_name: rename_images.exe
          asset_content_type: application/octet-stream